myproject/authors/urls.py
from django.urls import path

from . import views

app_name = 'authors'

urlpatterns = [
    path('', views.IndexPage.as_view(), name='authors'),
    path('create/', views.CreatePage.as_view(), name='create')
]

myproject/homepage/urls.py
from django.urls import path, register_converter
from django.views.generic.base import TemplateView

from .views import article_view_year, HomeView, ArticleView

app_name = "homepage"

class YearConverter():
    regex = r'[0-9]{4}'

    def to_python(self, value):
        return int(value)

    def to_url(self, value):
        return '%04d' % value

register_converter(YearConverter, 'year')

urlpatterns = [
    path('', TemplateView.as_view(template_name='homepage/index.html'), name="index"),
    path('articles/', ArticleView.as_view(), name="articles"),
    path('articles/<year:year>/', article_view_year, name='articles_year')
    # re_path(r'^articles/(?P<year>[0-9]{4})/$', article_view_year, name='articles_year')
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authors/', include('authors.urls')),
    path('play/', include('playground.urls')),
    path('', include('homepage.urls')),
]

myproject/playground/urls.py
from django.urls import path

from .views import PlaygroundView

app_name = 'playground'

urlpatterns = [
    path('', PlaygroundView.as_view(), name='playground')
]

myproject/authors/models.py
from django.db import models

class Author(models.Model):



    class Meta:
        verbose_name = 'Author'
        verbose_name_plural = 'Author'

# в БД записывается первое значение, второе отображается
    LEVELS = (
        ('J', 'Junior'),
        ('M', 'Middle'),
        ('S', 'Senior'),
    )

    first_name = models.fields.CharField(max_length=50)
    last_name = models.fields.CharField(max_length=50)
    level = models.fields.CharField(max_length=1, choices=LEVELS, default=LEVELS[0][0])
    email = models.fields.EmailField(null=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

# Create your models here.

myproject/playground/models.py
from django.db import models
from django.db.models.signals import post_save


class StudentInformation(models.Model):

    firsr_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    card_number = models.CharField(max_length=10, unique=True)
    email = models.EmailField()

    def __str__(self):
        return f"{self.firsr_name} {self.last_name}"


class Student(models.Model):

    class Meta:
        verbose_name = 'Student'
        verbose_name_plural = 'Students'

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class StudentInfo(models.Model):

    pass_id = models.CharField(max_length=10, unique=True, null=True)
    email = models.EmailField(unique=True)
    student = models.OneToOneField(
        Student,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='info'
    )

    def __str__(self):
        return f'{self.pass_id}'


def new_student_created(instance, created, **kwargs):
    DOMEN = 'playground.org'
    if not created:
        return
    count = Student.objects.filter(first_name=instance.first_name).count()
    email = f'{instance.first_name}{count}@{DOMEN}'.lower()
    StudentInfo.objects.create(email=email, student=instance)


post_save.connect(new_student_created, Student)


class Publisher(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return f'Publisher: {self.first_name} {self.last_name}'


class Articles(models.Model):
    title = models.CharField(max_length=250)
    # body
    date = models.DateField(auto_now=False)
    publisher = models.ForeignKey(
        Publisher,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return f'{self.title}'


class Category(models.Model):

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    label = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.label}'


class Shop(models.Model):

    class Meta:
        verbose_name = 'Shop'
        verbose_name_plural = 'Shops'

    title = models.CharField(max_length=100)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.title


# Create your models here.

myproject/authors/forms.py
from django import forms

from .models import Author

class AuthorForms(forms.ModelForm):

    class Meta:
        model = Author
        fields = ['first_name', 'last_name', 'email']

myproject/authors/views.py
from django.shortcuts import render, reverse, redirect
from django.views.generic import TemplateView, ListView

from .models import Author
from .forms import AuthorForms

class IndexPage(ListView):
    model = Author
    template_name = 'authors/index.html'
    context_object_name = 'authors'

class CreatePage(TemplateView):
    template_name = 'authors/create-page.html'

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['form'] = AuthorForms()
        return data

    def post(self, request):
        form = AuthorForms(request.POST)
        if form.is_valid():
            new_author = form.save(commit=False)
            new_author.email = 'default@email.ru'
            new_author.save()
            return redirect(reverse('authors:authors'))
        return render(request, self.template_name, {'form' : form})



# Create your views here.

myproject/homepage/views.py
from random import randint
from datetime import date, datetime, timedelta
from django.views.generic import TemplateView

from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from datetime import datetime
from django.http import HttpResponse

def today(count=20):
    days = []
    today = datetime.today() - timedelta(days=8)
    for i in range(count):
        print(i)
        day = today - timedelta(days=i)
        # print(day)
        for j in range(randint(2, 5)):
            print(str(i) + '-' + str(j))
            days.append(day.replace(hour=randint(0, 23)))
    return days
    # print(len(days))

class HomeView(TemplateView):
    template_name = 'homepage/index.html'

    def get(self, request, *args, **kwargs):
        return render(request, template_name=self.template_name)

class ArticleView(TemplateView):
    template_name = 'homepage/articles.html'

    def get(self, request, *args, **kwargs):
        myclass = MyClass()
        myclass.data = {
            'datakey': 'datavalue'
        }
        myclass.list = list(range(4, 8))
        args = {
            'articles': list(range(1, 4)),
            'title0': '',
            'title1': '<h3>title h3 1</h3>',
            'title2': '<h4>title h4 2</h4>',
            'myclass': myclass,
            'dates_my': today()
        }
        today()
        response = render(request, self.template_name, args)
        return response


def article_view_year(request, year):
    return HttpResponse(f'<h1>{year}</h1>')


class MyClass():
    foo = "foooooo"
    barr = 'baaaarr'
    def __repr__(self):
        return self.foo

myproject/playground/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from .models import Articles, Publisher

class PlaygroundView(TemplateView):
    template_name = 'playground/home.html'
    #
    # def get(self, request, *args, **kwargs):
    #     articles = Articles.objects.all()
    #     for article in articles:
    #         print(article.publisher)
    #     args = {
    #         'articles': articles
    #     }
    #     return render(request, self.template_name, args)

    def get_context_data(self, **kwargs):
        request = super().get_context_data(**kwargs)
        request['articles'] = Articles.objects.all()
        return request


# Create your views here.

myproject/templates/authors/base.html
<!doctype html>
<html lang="en">
<head>
{% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <title> {% block title%}Titles{% endblock title %} </title>
</head>
<body>
<div class="container">
<h1>Authors</h1>
    {% block body %}
    {% endblock body %}

</div>

<script src="{% static 'js/jquery.slim.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

myproject/templates/authors/create-page.html
{% extends 'authors/base.html' %}

{% block body %}
    <form action="" method="post">
    {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Отправить</button>

    </form>
{% endblock %}

myproject/templates/authors/index.html
{% extends 'authors/base.html' %}
{% load email_domain %}
{% load sharpnes_joke %}


{% block body %}
    <p>{% joke %}</p>
    <p>{% joke %}</p>
    <p>{% joke 0 %}</p>
    <p>{% joke 1 %}</p>
    <p>{% joke 3 %}</p>

        <ul class="list-group">
    {% for author in authors %}
        <li class="list-group-item">{{ author.first_name }} {{ author.last_name }} {{ author.email|domain }}</li>
    {% endfor %}
        </ul>
{% endblock %}

myproject/templates/base.html
<!doctype html>
<html lang="en">
<head>
{% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <title> {% block title%}Titles{% endblock title %} </title>
</head>
<body>
<div class="container">
    <br>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'homepage:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:articles' %}">Articles</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
        </div>
    </nav>

{#    <h1>Hello, world!</h1>#}

    {% block body %}
    {% endblock body %}
    <a href="{% url "homepage:index" %}">Index</a>
    <a href="{% url "homepage:articles" %}">Articles</a>
    <a href="{% url "playground:playground" %}">Playground</a>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static 'js/jquery.slim.min.js' %}"></script>
{#<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>#}
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

myproject/templates/homepage/articles.html
{% extends 'base.html' %}
{% block title%}Articles page{% endblock title %}
{% block body %}
    <h2>Articles page</h2>


    {% comment %}
    <ul class="list-group">
  <li class="list-group-item">Dapibus ac facilisis in</li>


  <li class="list-group-item list-group-item-primary">This is a primary list group item</li>
  <li class="list-group-item list-group-item-secondary">This is a secondary list group item</li>
  <li class="list-group-item list-group-item-success">This is a success list group item</li>
  <li class="list-group-item list-group-item-danger">This is a danger list group item</li>
  <li class="list-group-item list-group-item-warning">This is a warning list group item</li>
  <li class="list-group-item list-group-item-info">This is a info list group item</li>
  <li class="list-group-item list-group-item-light">This is a light list group item</li>
  <li class="list-group-item list-group-item-dark">This is a dark list group item</li>
</ul>
    {% endcomment %}
<ul class="list-group">
    {% for article in articles %}

        {% if article == 1 %}
        <h2>This article {{ article }} from if</h2>
        {% else %}
    {% cycle title1 title2 as title silent %}
<li class="list-group-item {% cycle '' 'list-group-item-secondary' 'list-group-item-danger'%}">Article #{{ article }} {{ title|safe }}</li>
        {% endif %}
        {% empty %}
        <h3>Sorry no articles</h3>
    {% endfor %}
{% cycle 'list-group-item-light' 'list-group-item-dark' as list_class silent %}
<li class="list-group-item {{ list_class }}">This is a light list group item</li>
  <li class="list-group-item {{ list_class }}">This is a dark list group item</li>
{% cycle list_class %}
<li class="list-group-item {{ list_class }}">This is a light list group item</li>
  <li class="list-group-item {{ list_class }}">This is a dark list group item</li>
</ul>
    {% autoescape off %}
<p>{% firstof title0 title1 title2 %}</p>
    {% endautoescape %}

<p>{{myclass.data.datakey|capfirst}}</p>
    {% if articles|length > 5 %}
        <h3>{{ articles|length }} &gt; 5</h3>
        {% else %}
        <h3>{{ articles|length }} &lt; 5</h3>
    {% endif %}
<p>{{myclass.list|length}}</p>

    {% for date in dates_my %}
        {% ifchanged date.month %}
        <h3>{{ date|date:'F' }}</h3>
        {% endifchanged %}
        {% ifchanged date.date %}
        <h3>{{ date|date:'d-m-Y' }}</h3>
            {% else %}
            ;
        {% endifchanged %}
        {{ date|date:'TIME_FORMAT' }}
    {% endfor %}

    <p>{% now 'DATE' %}</p>
    <p>{{ today }}</p>
    <p>{{ today|date:'SHORT_DATETIME_FORMAT' }}</p>

{% endblock body %}

myproject/templates/homepage/index.html
{% extends 'base.html' %}

{% block title%}Home page{% endblock title %}

{% block body %}
    <h2>Index page</h2>
{% endblock body %}

myproject/templates/playground/home.html
{% extends 'base.html' %}

{% block body %}
    <h1>Hello player</h1>
    <p>{{ articles }}</p>
    {% for article in articles %}
        <p>{{ article.publisher.first_name }} 1</p>
    {% endfor %}
{% endblock %}